# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import chatgraph.pb.userstate_pb2 as userstate__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in userstate_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserStateServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SelectUserState = channel.unary_unary(
                '/userstate.UserStateService/SelectUserState',
                request_serializer=userstate__pb2.UserStateId.SerializeToString,
                response_deserializer=userstate__pb2.UserState.FromString,
                _registered_method=True)
        self.InsertUserState = channel.unary_unary(
                '/userstate.UserStateService/InsertUserState',
                request_serializer=userstate__pb2.UserState.SerializeToString,
                response_deserializer=userstate__pb2.RequestStatus.FromString,
                _registered_method=True)
        self.UpdateUserState = channel.unary_unary(
                '/userstate.UserStateService/UpdateUserState',
                request_serializer=userstate__pb2.UserState.SerializeToString,
                response_deserializer=userstate__pb2.RequestStatus.FromString,
                _registered_method=True)
        self.DeleteUserState = channel.unary_unary(
                '/userstate.UserStateService/DeleteUserState',
                request_serializer=userstate__pb2.UserStateId.SerializeToString,
                response_deserializer=userstate__pb2.RequestStatus.FromString,
                _registered_method=True)
        self.GetAllUserStates = channel.unary_unary(
                '/userstate.UserStateService/GetAllUserStates',
                request_serializer=userstate__pb2.Void.SerializeToString,
                response_deserializer=userstate__pb2.UserStatesList.FromString,
                _registered_method=True)


class UserStateServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SelectUserState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertUserState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUserState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUserState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllUserStates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserStateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SelectUserState': grpc.unary_unary_rpc_method_handler(
                    servicer.SelectUserState,
                    request_deserializer=userstate__pb2.UserStateId.FromString,
                    response_serializer=userstate__pb2.UserState.SerializeToString,
            ),
            'InsertUserState': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertUserState,
                    request_deserializer=userstate__pb2.UserState.FromString,
                    response_serializer=userstate__pb2.RequestStatus.SerializeToString,
            ),
            'UpdateUserState': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUserState,
                    request_deserializer=userstate__pb2.UserState.FromString,
                    response_serializer=userstate__pb2.RequestStatus.SerializeToString,
            ),
            'DeleteUserState': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUserState,
                    request_deserializer=userstate__pb2.UserStateId.FromString,
                    response_serializer=userstate__pb2.RequestStatus.SerializeToString,
            ),
            'GetAllUserStates': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllUserStates,
                    request_deserializer=userstate__pb2.Void.FromString,
                    response_serializer=userstate__pb2.UserStatesList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'userstate.UserStateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('userstate.UserStateService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserStateService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SelectUserState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userstate.UserStateService/SelectUserState',
            userstate__pb2.UserStateId.SerializeToString,
            userstate__pb2.UserState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InsertUserState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userstate.UserStateService/InsertUserState',
            userstate__pb2.UserState.SerializeToString,
            userstate__pb2.RequestStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUserState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userstate.UserStateService/UpdateUserState',
            userstate__pb2.UserState.SerializeToString,
            userstate__pb2.RequestStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUserState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userstate.UserStateService/DeleteUserState',
            userstate__pb2.UserStateId.SerializeToString,
            userstate__pb2.RequestStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllUserStates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userstate.UserStateService/GetAllUserStates',
            userstate__pb2.Void.SerializeToString,
            userstate__pb2.UserStatesList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
