# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import chatgraph.pb.voll_pb2 as voll__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in voll_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MessageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendButton = channel.unary_unary(
                '/messagevoll.MessageService/SendButton',
                request_serializer=voll__pb2.MessageRequest.SerializeToString,
                response_deserializer=voll__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.SendList = channel.unary_unary(
                '/messagevoll.MessageService/SendList',
                request_serializer=voll__pb2.MessageRequest.SerializeToString,
                response_deserializer=voll__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.SendText = channel.unary_unary(
                '/messagevoll.MessageService/SendText',
                request_serializer=voll__pb2.MessageRequest.SerializeToString,
                response_deserializer=voll__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.TransferToHuman = channel.unary_unary(
                '/messagevoll.MessageService/TransferToHuman',
                request_serializer=voll__pb2.MessageRequest.SerializeToString,
                response_deserializer=voll__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.EndChat = channel.unary_unary(
                '/messagevoll.MessageService/EndChat',
                request_serializer=voll__pb2.MessageRequest.SerializeToString,
                response_deserializer=voll__pb2.MessageResponse.FromString,
                _registered_method=True)


class MessageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendButton(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransferToHuman(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendButton': grpc.unary_unary_rpc_method_handler(
                    servicer.SendButton,
                    request_deserializer=voll__pb2.MessageRequest.FromString,
                    response_serializer=voll__pb2.MessageResponse.SerializeToString,
            ),
            'SendList': grpc.unary_unary_rpc_method_handler(
                    servicer.SendList,
                    request_deserializer=voll__pb2.MessageRequest.FromString,
                    response_serializer=voll__pb2.MessageResponse.SerializeToString,
            ),
            'SendText': grpc.unary_unary_rpc_method_handler(
                    servicer.SendText,
                    request_deserializer=voll__pb2.MessageRequest.FromString,
                    response_serializer=voll__pb2.MessageResponse.SerializeToString,
            ),
            'TransferToHuman': grpc.unary_unary_rpc_method_handler(
                    servicer.TransferToHuman,
                    request_deserializer=voll__pb2.MessageRequest.FromString,
                    response_serializer=voll__pb2.MessageResponse.SerializeToString,
            ),
            'EndChat': grpc.unary_unary_rpc_method_handler(
                    servicer.EndChat,
                    request_deserializer=voll__pb2.MessageRequest.FromString,
                    response_serializer=voll__pb2.MessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'messagevoll.MessageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('messagevoll.MessageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MessageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendButton(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messagevoll.MessageService/SendButton',
            voll__pb2.MessageRequest.SerializeToString,
            voll__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messagevoll.MessageService/SendList',
            voll__pb2.MessageRequest.SerializeToString,
            voll__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messagevoll.MessageService/SendText',
            voll__pb2.MessageRequest.SerializeToString,
            voll__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransferToHuman(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messagevoll.MessageService/TransferToHuman',
            voll__pb2.MessageRequest.SerializeToString,
            voll__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messagevoll.MessageService/EndChat',
            voll__pb2.MessageRequest.SerializeToString,
            voll__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ActionsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCampaignID = channel.unary_unary(
                '/messagevoll.ActionsService/GetCampaignID',
                request_serializer=voll__pb2.CampaignName.SerializeToString,
                response_deserializer=voll__pb2.CampaignDetails.FromString,
                _registered_method=True)
        self.GetCampaignsList = channel.unary_unary(
                '/messagevoll.ActionsService/GetCampaignsList',
                request_serializer=voll__pb2.Void.SerializeToString,
                response_deserializer=voll__pb2.CampaignsList.FromString,
                _registered_method=True)
        self.GetTabulationID = channel.unary_unary(
                '/messagevoll.ActionsService/GetTabulationID',
                request_serializer=voll__pb2.TabulationName.SerializeToString,
                response_deserializer=voll__pb2.TabulationDetails.FromString,
                _registered_method=True)
        self.GetTabulationsList = channel.unary_unary(
                '/messagevoll.ActionsService/GetTabulationsList',
                request_serializer=voll__pb2.Void.SerializeToString,
                response_deserializer=voll__pb2.TabulationsList.FromString,
                _registered_method=True)


class ActionsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCampaignID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCampaignsList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTabulationID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTabulationsList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ActionsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCampaignID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCampaignID,
                    request_deserializer=voll__pb2.CampaignName.FromString,
                    response_serializer=voll__pb2.CampaignDetails.SerializeToString,
            ),
            'GetCampaignsList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCampaignsList,
                    request_deserializer=voll__pb2.Void.FromString,
                    response_serializer=voll__pb2.CampaignsList.SerializeToString,
            ),
            'GetTabulationID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTabulationID,
                    request_deserializer=voll__pb2.TabulationName.FromString,
                    response_serializer=voll__pb2.TabulationDetails.SerializeToString,
            ),
            'GetTabulationsList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTabulationsList,
                    request_deserializer=voll__pb2.Void.FromString,
                    response_serializer=voll__pb2.TabulationsList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'messagevoll.ActionsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('messagevoll.ActionsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ActionsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCampaignID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messagevoll.ActionsService/GetCampaignID',
            voll__pb2.CampaignName.SerializeToString,
            voll__pb2.CampaignDetails.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCampaignsList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messagevoll.ActionsService/GetCampaignsList',
            voll__pb2.Void.SerializeToString,
            voll__pb2.CampaignsList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTabulationID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messagevoll.ActionsService/GetTabulationID',
            voll__pb2.TabulationName.SerializeToString,
            voll__pb2.TabulationDetails.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTabulationsList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messagevoll.ActionsService/GetTabulationsList',
            voll__pb2.Void.SerializeToString,
            voll__pb2.TabulationsList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
